import Image from 'next/image'

export const SocialsList = () => {
  return (
    <ul className='socialsList justify-center'>
      <li>
        <a
          href='https://www.facebook.com/groups/1233181850502151'
          target='_blank'
          rel='noreferrer'
        >
          <Image
            src='/icons/facebook.svg'
            width={53}
            height={53}
            alt='Facebook'
          ></Image>
        </a>
      </li>
      <li>
        <a
          href='https://www.instagram.com/chicagocraftclub/'
          target='_blank'
          rel='noreferrer'
        >
          <Image
            src='/icons/instagram.svg'
            width={53}
            height={53}
            alt='Instagram'
          ></Image>
        </a>
      </li>
      <li>
        <a
          href='https://discord.gg/ekJwuzzF3T'
          target='_blank'
          rel='noreferrer'
        >
          <Image
            src='/icons/discord.svg'
            width={53}
            height={53}
            alt='Discord'
          ></Image>
        </a>
      </li>
      <li>
        <a
          href='https://www.tiktok.com/@chicagocraftclub'
          target='_blank'
          rel='noreferrer'
        >
          <Image
            src='/icons/tiktok.svg'
            width={53}
            height={53}
            alt='Tiktok'
          ></Image>
        </a>
      </li>
      <li>
        <a
          href='https://app.geneva.com/invite/3a4ab924-4f52-4b7a-b0d5-c234ba74ea39'
          target='_blank'
          rel='noreferrer'
        >
          <Image
            src='/geneva-flower-vector-white.svg'
            width={53}
            height={53}
            alt='Geneva'
          ></Image>
        </a>
      </li>
    </ul>
  )
}
